### PR TITLE
React Landing page

### PR DESCRIPTION
**Pull request by irfankhan10**
`pip install -r requirements.txt -y`
`cd docs`
(update git submodules and the build html.)
(Once HTML is built, run this command)
`sphinx-serve -b build`

### CODE REVIEW

**Comment by dimkart** [comment]
@irfankhan10 Thanks, please check comments below:

- Under LAMBEQ, it says something about quantum hardware. Please replace with current phrase "Natural Language Processing on Quantum Computers"
- Cover image is now much smaller than before, it's like something is missing there
- The "pip install lambeq" button doesn't do anything, at least in my browser.
- lambeq-support email is the old one. New one: lambeq-support@quantinuum.com
- Get in Touch and Publications buttons do not work unless you click the tiny description they have, which I guess it's not the intended behaviour.
- Publications button lead to the general publications page instead of the Oxford's team page as before.
- In footer, "Lambeq" is included as one of the links. I suppose this might be OK if there is one footer for all product. However, if this is intended behaviour, please change to "lambeq" or "λambeq".

**Comment by dimkart** [comment]
@irfankhan10 Also: from the discord link, remove last /, since otherwise does not work as intended.

**Comment by neiljdo** [comment]
@dimkart, @irfankhan10 I'll work on the fixes that doesn't require updating the `quantinuum-sphinx` plugin (if there's any).

**Comment by neiljdo** [comment]
@dimkart for the publications page, the old URL has been replaced. There's also a new [page](https://www.quantinuum.com/compositional-intelligence) now for the Compositionl Intelligence team (which is where I think we should link to). However, if you click on the "Explore Publications", you'll be forwarded to a [page](https://www.quantinuum.com/research/research-areas#publications) with a search bar/filter that contains all the publications across all the teams. Sadly, there's no way yet to preselect a filter on that page and have that reflected in the url.

**Comment by dimkart** [comment]
> @dimkart for the publications page, the old URL has been replaced. There's a new [page](https://www.quantinuum.com/compositional-intelligence) for the Compositional Intelligence team (which is where I think we should link to). However, if you click on the "Explore Publications", you'll be forwarded to a [page](https://www.quantinuum.com/research/research-areas#publications) with a search bar/filter that contains all the publications across all the teams. Sadly, there's no way yet to preselect a filter on that page and have that reflected in the url.

Let's link to the CI page.

**Comment by irfankhan10** [comment]
Thanks Dimitri, I will come back to this at 5PM

**Comment by neiljdo** [comment]
@irfankhan10 @dimkart this is how it looks if we replace the graphic lambeq logo with the text logo in the rest of the pages.

image

**Comment by dimkart** [comment]
> @irfankhan10 @dimkart this is how it looks if we replace the graphic lambeq logo with the text logo in the rest of the pages.
> 

That's not a logo, it's just the name of the product which is repeated below. Why should we change the current logo anyway?

**Comment by dimkart** [comment]
If we want to change the logo with something that also contains the name of the product, let's at least do something similar to the Nexus approach (below), e.g. lambeq's logo as a first letter of the word lambeq, e.g. "(λ)ambeq" with (λ) to be the current logo.

image

**Comment by neiljdo** [comment]
> If we want to change the logo with something that also contains the name of the product, let's at least do something similar to the Nexus approach (below), e.g. lambeq's logo as a first letter of the word lambeq, e.g. "(λ)ambeq" with (λ) to be the current logo.
> 
> image

@irfankhan10 , in relation to making the logos and other assets consistent across all the docs sites, would you know if we have a dedicated graphics designer that can create these assets across the board so we ensure coherence and consistency?

**Comment by irfankhan10** [comment]
Lets bring this up on monday. This PR is to the first step to bring react into the docs framework. It will not resolve all problems.

**Comment by neiljdo** [comment]
Closing this and migrating to #15.

**Comment by irfankhan10** [comment]
Closing this PR in favour of Aidan's PR. @dimkart and @neiljdo, I have translated feedback here to the PR by @aidancq.

**Pull request closed without merging**
